import React from "react";

import "./circulateAnimation.css"
const CirculateAnimation = () => {
    return(
        <div className="main-rap-wrap">
            <div className="wrap">
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                <div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div><div className="c"></div>
                
        </div>  
    </div>  
    );
}

export default CirculateAnimation;